README.md
Some changes to `README.md` for clarity, in particular upon how the spec process interacts with the repo.
=> R4R: Suggested process changes

.gitattributes, README.md, spec/ics-template.md
Add a simple template for easy copy-paste into new ICS standards.
Update README to reference ICS 1.
=> Add ICS template; update README

spec/ics-1-ics-standard/README.md
Link to PROCESS.md instead of duplicating stages
=> Minor updates to ICS 1

spec/ics-1-ics-standard/README.md
Closes https://github.com/cosmos/ics/issues/62
- Provide examples of Golang (structs) and CoffeeScript (algorithms) syntax for pseudocode
- Add definitions section prior to desired properties section
=> ICS 1 formatting & organization updates

.circleci/config.yml, Makefile, scripts/check_sections.py
Closes https://github.com/cosmos/ics/issues/84
=> Add CI to check sections

scripts/check_links.py, spec/ics-1-ics-standard/README.md, spec/ics-18-relayer-algorithms/README.md, spec/ics-23-vector-commitments/README.md, spec/ics-24-host-requirements/README.md, spec/ics-3-connection-semantics/README.md
=> Fix CI, a bit of cleanup

README.md, deps.png
=> Fix README

.circleci/config.yml, deps.png, scripts/check_dependencies.py, scripts/check_syntax.sh, scripts/tslint.json, spec/ics-1-ics-standard/README.md, spec/ics-18-relayer-algorithms/README.md, spec/ics-2-consensus-verification/README.md, spec/ics-2-consensus-verification/VERIFIER.md, spec/ics-23-vector-commitments/README.md, spec/ics-24-host-requirements/README.md, spec/ics-3-connection-semantics/README.md
Closes https://github.com/cosmos/ics/issues/102
=> Syntax experimentation

spec/ics-24-host-requirements/README.md
Closes https://github.com/cosmos/ics/issues/110
=> Basic data availability requirements

README.md, deps.png, ibc/5_IBC_DESIGN_PATTERNS.md, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-026-relayer-module/README.md
Closes https://github.com/cosmos/ics/issues/87
Closes https://github.com/cosmos/ics/issues/118
=> ICS 26: Relayer Module

README.md
=> Fix ICS 1 link

spec/ics-001-ics-standard/README.md, spec/ics-002-consensus-verification/README.md, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-018-relayer-algorithms/README.md, spec/ics-023-vector-commitments/README.md, spec/ics-024-host-requirements/README.md, spec/ics-025-handler-interface/README.md, spec/ics-026-relayer-module/README.md, spec/ics-template.md
Closes https://github.com/cosmos/ics/issues/124
=> Switch CC0 to Apache 2.0

spec/ics-002-consensus-verification/README.md, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md
Closes https://github.com/cosmos/ics/issues/111
Quite sure this is safe in principle but will require further proofs later.
=> Handle multiple state roots

Makefile, README.md, spec.pdc, spec.pdf
Not the prettiest, but it will do for now.
=> Add basic PDF w/line numbers

Makefile, README.md, assets/deps.png, spec/ics-020-fungible-token-transfer/Makefile, spec/ics-020-fungible-token-transfer/README.md, spec/ics-020-fungible-token-transfer/packets.proto, spec/ics-026-relayer-module/README.md, spec/ics-026-relayer-module/datagrams.proto
Ref #9.
First application-level spec. Work in progress. Also should cover denom tracking (https://github.com/cosmos/ics/issues/9#issuecomment-511355528).
=> ICS 020: Fungible Token Transfer

assets/deps.png, spec.pdc, spec.pdf, spec/ics-002-consensus-verification/README.md, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-005-port-allocation/README.md, spec/ics-018-relayer-algorithms/README.md, spec/ics-023-vector-commitments/README.md, spec/ics-024-host-requirements/README.md, spec/ics-025-handler-interface/README.md, spec/ics-026-relayer-module/README.md, spec/ics-template.md
Closes https://github.com/cosmos/ics/issues/139
Rough reasoning for now, to be further formalized later (ref https://github.com/cosmos/ics/pull/100).
=> Properties; invariants; rough reasoning about proofs

Makefile, spec.pdf, spec/ics-002-consensus-verification/Makefile, spec/ics-002-consensus-verification/README.md, spec/ics-002-consensus-verification/data-structures.proto, spec/ics-003-connection-semantics/Makefile, spec/ics-003-connection-semantics/README.md, spec/ics-003-connection-semantics/data-structures.proto, spec/ics-004-channel-and-packet-semantics/Makefile, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-004-channel-and-packet-semantics/data-structures.proto
Closes https://github.com/cosmos/ics/issues/66 though will need revision later.
=> Add data structures in proto3 (wip)

Makefile, misc/aspell_dict, scripts/make_pdf.sh, spec.pdc, spec.pdf, spec/ics-002-client-semantics/README.md, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-005-port-allocation/README.md, spec/ics-024-host-requirements/README.md, spec/ics-026-relayer-module/README.md
Closes https://github.com/cosmos/ics/issues/183
Closes https://github.com/cosmos/ics/issues/178
Ref https://github.com/cosmos/ics/issues/181
Ref #179 
Ref https://github.com/cosmos/ics/issues/175
Closes #170 
Ref #160 (only for ICS 24 in this PR)
=> Host state machine alterations; updates accordingly

spec.pdf, spec/ics-003-connection-semantics/data-structures.proto, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-004-channel-and-packet-semantics/data-structures.proto
Closes https://github.com/cosmos/ics/issues/169
=> Start indexing at 1 for sequences & enums

spec.pdf, spec/ics-024-host-requirements/README.md
Ref https://github.com/cosmos/ics/issues/169#issuecomment-518020081
=> Add note on non-empty identifiers

spec.pdf, spec/ics-005-port-allocation/README.md
Closes https://github.com/cosmos/ics/issues/171
=> Explain how modules will use ports

spec.pdf, spec/ics-024-host-requirements/README.md
Closes https://github.com/cosmos/ics/issues/182
=> Define module system in ICS 24

spec.pdf, spec/ics-002-client-semantics/README.md, spec/ics-005-port-allocation/README.md, spec/ics-020-fungible-token-transfer/README.md, spec/ics-024-host-requirements/README.md, spec/ics-026-relayer-module/README.md
Closes https://github.com/cosmos/ics/issues/175
=> Throw exceptions instead of returning false

spec/ics-024-host-requirements/README.md
Closes https://github.com/cosmos/ics/issues/177
=> Keyspace table

spec.pdf, spec/ics-002-client-semantics/README.md
Closes https://github.com/cosmos/ics/issues/165
=> Briefly discuss third-party introductions

spec/ics-005-port-allocation/README.md
Closes https://github.com/cosmos/ics/issues/179
=> Discuss possiblity of module manager

spec.pdf, spec/ics-002-client-semantics/README.md
Closes https://github.com/cosmos/ics/issues/163
=> Add note on custom execution logic

spec.pdf, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-005-port-allocation/README.md, spec/ics-025-handler-interface/README.md, spec/ics-026-relayer-module/README.md
Closes https://github.com/cosmos/ics/issues/181
=> Add notes on authentication mechanism

spec.pdf, spec/ics-018-relayer-algorithms/README.md
Closes https://github.com/cosmos/ics/issues/166
=> Discuss ordering constraints

misc/aspell_dict, spec.pdf, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-025-handler-interface/README.md
Closes https://github.com/cosmos/ics/issues/180
=> Clarify version negotiation

spec.pdf, spec/ics-004-channel-and-packet-semantics/README.md
=> Connection hops should be length 1

misc/aspell_dict, spec.pdf, spec/ics-002-client-semantics/README.md, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-005-port-allocation/README.md, spec/ics-023-vector-commitments/README.md, spec/ics-024-host-requirements/HostRequirements.agda, spec/ics-024-host-requirements/README.md, spec/ics-026-relayer-module/README.md
Various, from review & as I read through.
=> Misc cleanup

spec.pdf, spec/ics-004-channel-and-packet-semantics/README.md
Cleanup, separate common logic into helper functions.
=> ICS 4 refactors

ibc/1_IBC_ARCHITECTURE.md, ibc/2_IBC_DESIGN_PRINCIPLES.md, ibc/4_IBC_USECASES.md, ibc/5_IBC_DESIGN_PATTERNS.md, spec/ics-002-client-semantics/README.md, spec/ics-003-connection-semantics/README.md, spec/ics-005-port-allocation/README.md, spec/ics-023-vector-commitments/README.md
Fixing various typos tracked in my review sheet. Split as much as possible into commits in case some are wrong ...
=> Fixing various typos

misc/aspell_dict, spec.pdf, spec/ics-003-connection-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-023-vector-commitments/README.md, spec/ics-024-host-requirements/README.md
Ref #145 
Closes #258 
Closes #269
=> Remaining rc3 feedback in preparation for rc4

spec.pdf, spec/ics-004-channel-and-packet-semantics/README.md
Closes https://github.com/cosmos/ics/issues/296
=> Commit to packet timeout

misc/aspell_dict, spec/ics-003-connection-semantics/README.md, spec/ics-003-connection-semantics/state.png, spec/ics-004-channel-and-packet-semantics/channel-state-machine.png, spec/ics-004-channel-and-packet-semantics/dataflow.png, spec/ics-004-channel-and-packet-semantics/packet-state-machine.png, spec/ics-004-channel-and-packet-semantics/packet-transit.png, spec/ics-018-relayer-algorithms/README.md, spec/ics-026-routing-module/README.md
Ref https://github.com/cosmos/ics/issues/217
=> Specify detailed example relayer algorithm

_layouts/ics.html, spec/ics-template.md
Ref https://github.com/cosmos/ics/issues/286
=> Alter spec template

spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-018-relayer-algorithms/README.md, spec/ics-024-host-requirements/README.md
Closes https://github.com/cosmos/ics/issues/313
Closes https://github.com/cosmos/ics/issues/217
=> Define & use log emitting & reading interface

ideation/ics-027-direct-interchain-exchange/ReadMe.md
As a separate PR since I can't push to the remote of https://github.com/cosmos/ics/pull/271.
=> Direct interchain exchange protocol ideation

ideation/zkps-interchain.md
Closes https://github.com/cosmos/ics/issues/268.
Work in progress.
=> Start interchain ZKPs brainstorming document

README.md, assets/deps.png, spec.pdf, spec/ics-009-loopback-client/Makefile, spec/ics-009-loopback-client/README.md
Loop-back client for interacting through the IBC interface with modules on the local ledger.
Closes https://github.com/cosmos/ics/issues/352.
=> ICS 9 (loopback client)

spec.pdf, spec/ics-006-solo-machine-client/README.md
Closes https://github.com/cosmos/ics/issues/359
=> Fix ICS 6 inconsistencies

spec.pdf, spec/ics-002-client-semantics/README.md, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-006-solo-machine-client/README.md, spec/ics-007-tendermint-client/README.md
Closes https://github.com/cosmos/ics/issues/358
=> Move commitment mechanism to client-type-specific specs

misc/aspell_dict, spec.pdf, spec/ics-007-tendermint-client/README.md, spec/ics-024-host-requirements/README.md
Closes https://github.com/cosmos/ics/issues/366
Closes https://github.com/cosmos/ics/issues/365
Closes https://github.com/cosmos/ics/issues/364
Thanks @AdityaSripal & @fedekunze.
=> Fixes to ICS 7 from review

media/README.md
To add media & press to `cosmos.network/ibc` resources: https://deploy-preview-755--cosmos-staging.netlify.com/ibc
=> Add media section to cosmos.network/ibc

spec/ics-003-connection-semantics/README.md, spec/ics-009-loopback-client/README.md
=> Fix call type inconsistencies

misc/aspell_dict, spec.pdf, spec/ics-007-tendermint-client/README.md
Closes https://github.com/cosmos/ics/issues/379
=> Add note on "would-have-been-fooled" handling

spec/ics-004-channel-and-packet-semantics/README.md
Closes https://github.com/cosmos/ics/issues/376
=> Clarify timeouts

ECOSYSTEM.md, README.md, spec.pdc, spec/ics-010-grandpa-client/Makefile, spec/ics-010-grandpa-client/README.md
This is a initial spec for GRANDPA finality gadget.
In future versions, we will add a verification for TrustPeriod if
necessary and provide pseudocode for verifying justification.
=> ICS 10: GRANDPA client

spec.pdf, spec/ics-024-host-requirements/README.md
Closes https://github.com/cosmos/ics/issues/414
=> Alter identifier requirements

spec/ics-004-channel-and-packet-semantics/README.md
nextSequenceAck belongs to a source-side end of a channel.
=> ICS 4: Fix acknowledgement processing

misc/aspell_dict, spec.pdf, spec/ics-002-client-semantics/README.md
Closes https://github.com/cosmos/ics/issues/418
=> Add bit on governance intervention

spec.pdf, spec/ics-004-channel-and-packet-semantics/README.md, spec/ics-025-handler-interface/README.md, spec/ics-026-routing-module/README.md
Closes https://github.com/cosmos/ics/issues/440
=> Remove cleanupPacket, update references

spec.pdf, spec/ics-003-connection-semantics/README.md
Closes https://github.com/cosmos/ics/issues/432
=> Fix consensus state check

spec.pdf, spec/ics-018-relayer-algorithms/README.md
Closes https://github.com/cosmos/ics/issues/436
=> Fix mistake in ICS 18

spec/ics-006-solo-machine-client/README.md
Closes https://github.com/cosmos/ics/issues/470
Closes https://github.com/cosmos/ics/issues/475
=> Solo machine updates

README.md
=> docs: fix-deadlink

spec/app/ics-029-fee-payment/README.md
It was a little hard to read in the rendered format
=> fix relayer incentive formatting

.github/workflows/link-check.yml
Adds the same link checker that's used in Tendermint. See [here](https://github.com/tendermint/tendermint/blob/master/.github/workflows/linkchecker.yml).
=> Add Markdown link checker to ensure link integrity

spec/core/ics-024-host-requirements/README.md
=> Fix ICS024 paths

spec/app/ics-027-interchain-accounts/README.md
Addresses remaining issues from #618 and #616 reviews
=> ICS27 Spec Improvements

spec/core/ics-005-port-allocation/README.md
=> Minor grammar fix

spec/app/ics-027-interchain-accounts/README.md
Some suggestions to improve the formatting and add more consistency to the text.
=> ics-27 consistency and formatting improvements

spec/client/ics-008-wasm-client/README.md
From discussion with @ethanfrey , the motiviations for ICS8 are not clearly articulated in the spec and to the wider community.
=> ICS8: Add clearer WASM client motivation

spec/app/ics-020-fungible-token-transfer/README.md
Closes https://github.com/cosmos/ibc/issues/565
Replace `denomination` with `denom` in `FungibleTokenPacketData`.
=> IBC20: Replace denomination with denom in packet data

meta/ROADMAP.md
=> Meta: update roadmap

spec/app/ics-028-cross-chain-validation/technical_specification.md
Closes https://github.com/cosmos/ibc/issues/739
=> ICS28: vsc will not mature if there are no updates from provider

spec/app/ics-030-middleware/README.md
Makes ICS30 consistent with https://github.com/cosmos/ibc/pull/731
=> ICS30: Simplify sendPacket interface

spec/app/ics-027-interchain-accounts/README.md
Makes ICS27 consistent with https://github.com/cosmos/ibc/pull/731
=> ICS27: Simplify sendPacket interface

spec/core/ics-004-channel-and-packet-semantics/README.md
Closes: https://github.com/cosmos/ibc/issues/645
Removes OPEN check on TimeoutPacket
=> Fix Optimistic Sends

spec/app/ics-020-fungible-token-transfer/README.md
=> ICS20: Update Callbacks

README.md
Used stages from https://github.com/cosmos/ibc/blob/master/meta/PROCESS.md
Added the links I know of. Please open additional PRs if I miss a completed implementation
=> META: Update README Table

README.md
With link to Chinese translation.
=> docs: add translations section in readme

spec/core/ics-004-channel-and-packet-semantics/README.md
Closes https://github.com/cosmos/ibc/issues/827
=> ICS4: Wrong inequality for timeoutPacket

spec/app/ics-028-cross-chain-validation/system_model_and_properties.md
=> ICS28: Adds precision to wording for sumUnbonding definition

CHANGELOG.md, spec/app/ics-027-interchain-accounts/README.md
=> ICS27: add explanation about expected behavior for controller modules `onRecvPacket` callback

spec/app/ics-721-nft-transfer/README.md
=> Fix formatting and date

spec/client/ics-007-tendermint-client/README.md
=> ICS07: change reference from ICS 8 to ICS 23

spec/app/ics-028-cross-chain-validation/data_structures.md, spec/app/ics-028-cross-chain-validation/methods.md, spec/app/ics-028-cross-chain-validation/overview_and_basic_concepts.md, spec/app/ics-028-cross-chain-validation/technical_specification.md
Reflects the ICS implementation refactoring https://github.com/cosmos/interchain-security/pull/354
=> ICS28: Proposal naming refactors

CHANGELOG.md, spec/core/ics-003-connection-semantics/README.md
=> ICS-3: update `Version` field

.github/CODEOWNERS
Welcome @angbrav to the selective club of IBC spec code owners! 🥳
=> add angbrav as code owner

spec/app/ics-020-fungible-token-transfer/README.md, spec/app/ics-027-interchain-accounts/README.md, spec/app/ics-029-fee-payment/README.md, spec/app/ics-030-middleware/README.md, spec/app/ics-721-nft-transfer/README.md, spec/core/ics-004-channel-and-packet-semantics/README.md
=> ICS 04: return sequence number in `sendPacket`

spec/app/ics-020-fungible-token-transfer/README.md, spec/app/ics-027-interchain-accounts/README.md, spec/app/ics-028-cross-chain-validation/README.md, spec/app/ics-029-fee-payment/README.md, spec/app/ics-030-middleware/README.md, spec/app/ics-721-nft-transfer/README.md, spec/client/ics-006-solo-machine-client/README.md, spec/client/ics-007-tendermint-client/README.md, spec/client/ics-008-wasm-client/README.md, spec/client/ics-010-grandpa-client/README.md, spec/core/ics-002-client-semantics/README.md, spec/core/ics-003-connection-semantics/README.md, spec/core/ics-004-channel-and-packet-semantics/README.md, spec/core/ics-005-port-allocation/README.md, spec/core/ics-023-vector-commitments/README.md, spec/core/ics-024-host-requirements/README.md, spec/core/ics-025-handler-interface/README.md, spec/core/ics-026-routing-module/README.md, spec/ics-001-ics-standard/README.md, spec/ics-template.md, spec/relayer/ics-018-relayer-algorithms/README.md
Updates the sections for example and other implementations
=> chore: update example implementations

spec/core/ics-004-channel-and-packet-semantics/README.md
=> fix: check acknowledgement is not empty

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
=> Fix upgrade crossing hello

spec/relayer/ics-018-relayer-algorithms/README.md
=> ICS 18: crossing hellos in connection and channel handshake are not supported

spec/core/ics-026-routing-module/README.md
=> ics26: match connection datagrams and handlers to ics03 function signatures

spec/client/ics-006-solo-machine-client/README.md
[The `sequence` is in the `ClientState` in ibc-go](https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/06-solomachine/client_state.go#L24).
=> ics 06: putting sequence in `ClientState`

meta/CONTRIBUTING.md
updating old links to https://discord.gg/cosmosnetwork
=> discord security patch CONTRIBUTING.md

spec/core/ics-004-channel-and-packet-semantics/README.md, spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
No logic changed, just consistent naming across the spec, style improvements and some small fixes.
I will merge this after other opened PRs to avoid merge conflicts in them.
=> ICS 04 (upgrades): improvements for readability and inconsistency fixes

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md, spec/core/ics-026-routing-module/UPGRADES.md
=> ICS26: updated upgrade callback signatures

README.md, assets/interchain-standards.png
Update repo cover with new branding image
=> Update Repo Cover

meta/STANDARDS_COMMITTEE.md
=> update standards committee

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
- Add explanation of out of sequence logic
- Optimize cancellation
=> ICS4: Optimize Cancel

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
=> ICS4: Move channel proof in TRY to the front

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
=> rename UpgradeTimeout to Timeout

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
Opening this PR, after discussion with Aditya, to clarify some comments in the protocol specs.
=> specs comments details clarification

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
Updates for ibc-go changes [here](https://github.com/cosmos/ibc-go/pull/5638/files).
=> ICS4 (upgrades): open can complete after counterparty reinits

spec/core/ics-004-channel-and-packet-semantics/README.md
=> fix: delete auxiliary upgrade information during channel closure

spec/core/ics-026-routing-module/README.md, spec/core/ics-026-routing-module/UPGRADES.md
**Description:**
Some minor typos are fixed.
**Test:**
No test required because only specs are modified.
=> Fix some minor typos

spec/app/ics-020-fungible-token-transfer/README.md
To sync with changes in https://github.com/cosmos/ibc-go/pull/6576
=> ICS20v2 nit: rename `ForwardingInfo` to `Forwarding`

spec/app/ics-020-fungible-token-transfer/README.md
ref: https://github.com/cosmos/ibc/pull/1090#discussion_r1627279389
=> ICS20v2: delete previously forwarded packet

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
I may misunderstand something about crossing hello, but isn't this code comment wrong somehow?
=> ICS04: fix a code comment in chanUpgradeTry in UPGRADES.md

spec/core/v2/ics-004-channel-and-packet-semantics/README.md
This is an alternative specification of events that only specifies which events to emit in the minimal handlers necessary without explicitly specifying how. This allows different implementors to make different choices to match their specific event systems.
=> ICS4: Event Emission Specification (NO PSEUDOCODE)
