cosmos/ibc

README.md

I think we should optimize the design of the specification process mostly for understandability & efficiency for future readers of the spec, and combining the proposal (rationale) & specification into one file seems like that will make it easier. Additional documentation can be included if desired.

R4R: One file for both proposals and specifications

---

PROCESS.md
README.md

Updates from feedback last week at the IBC ecosystem call:
- Move TC39 process description to separate file
- List merged draft-stage-or-later specifications in README
- Clarify required approvals at different process stages
- Clarify required dual-implementation compatibility before standard finalization
Also several other updates I think are prudent:
- Combines the "proposal" and "draft" stages, which don't seem necessary to separate
- Clarify what specific stages correspond to in terms of Git state / PR approvals / etc.

Process updates from feedback

---

spec/ics-024-host-requirements/README.md

Closes https://github.com/cosmos/ics/issues/125

Rename "module" to "port", clarify usage

---

spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-004-channel-and-packet-semantics/dataflow.png
spec/ics-004-channel-and-packet-semantics/dataflow.tex

Ref https://github.com/cosmos/ics/issues/138#issuecomment-509029441

Future compatibility with multi-hop routing

---

.circleci/config.yml
Makefile
spec/ics-002-consensus-verification/README.md
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-025-handler-interface/README.md
spec/ics-026-relayer-module/Makefile
spec/ics-026-relayer-module/README.md
spec/ics-026-relayer-module/datagrams.proto

Closes https://github.com/cosmos/ics/issues/134
Closes https://github.com/cosmos/ics/issues/146
Closes https://github.com/cosmos/ics/issues/148
Depends on https://github.com/cosmos/ics/pull/150

Update relayer module & handler interface; loopback; closure handling; proto3 schemas

---

spec.pdc
spec.pdf
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-020-fungible-token-transfer/README.md
spec/ics-024-host-requirements/README.md
spec/ics-025-handler-interface/README.md

A few alterations which didn't make it in `1.0.0-rc0`, and responses to specification feedback.

Start 1.0.0-rc1

---

spec/ics-024-host-requirements/README.md

Under `getConsensusState`,
> `getConsensusState` MUST return the consensus state for the consensus algorithm of the host chain at the specified height, for all heights greater than zero and less than or equal to the current height.
For some cases `getConsensusState` will not be able to return the consensus state with height of `0 < _ < current`. For efficiency, the chains might choose to prune the states and (if the pruning happens for past enough states) the impl will still work, so the restriction should be RECOMMENDED.

Fix 24/getConsensusState

---

README.md
spec/ics-001-ics-standard/README.md
spec/ics-002-client-semantics/README.md
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-018-relayer-algorithms/README.md
spec/ics-020-fungible-token-transfer/README.md
spec/ics-023-vector-commitments/README.md
spec/ics-024-host-requirements/README.md
spec/ics-025-handler-interface/README.md
spec/ics-026-relayer-module/README.md

Closes https://github.com/cosmos/ics/issues/185

Clarify scope of IBC

---

spec/ics-027-interchain-account/README.md

I read carefully after merging. And I found some things needed to be fixed. 🙏
I removed  "the appropriate signatures" in the sentence "The transaction bytes contain the transaction itself & the appropriate signatures". And I fixed a typo that I found.
@cwgoes And, It seems that you use "serialise/deserialise". But, my English dictionary says it as "serialize/deserialize". I'm not sure that which one is correct or both are correct. But, I used "serialize/deserialize". So, there are two types of "serializ(s)e/deserializ(s)e" in this document. Do you think that it is better to use only "serialise/deserialise"?

Fix ics-027

---

misc/aspell_dict
spec.pdf
spec/ics-002-client-semantics/README.md
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-006-solo-machine-client/README.md
spec/ics-007-tendermint-client/README.md
spec/ics-024-host-requirements/README.md

Closes https://github.com/cosmos/ics/issues/345
Closes https://github.com/cosmos/ics/issues/346

Update paths for consistency; revise ICS 2 for client type sub-specs

---

ibc/2_IBC_ARCHITECTURE.md

'arbitrary topologies' instead of 'arbitrarily topologies'

docs: small grammar mistake

---

ecosystem/README.md

Edited two small typos in the text, and changed future meeting date to `TBD` since the one that was there has already happened.

DOC: small typos in ecosystem/README.md

---

spec/ics-002-client-semantics/README.md

I think here `hash()` is needed.

Fix missing hash() in ICS 02

---

spec/ics-004-channel-and-packet-semantics/README.md

`channelEnd.connectionHops` is supposed to mean its own connection. (not counterparty's)
It is possible to put a notable further work of 'reversed' hops semantics only if we query multiple connection first. (Doing so doesn't seem clear now I think)

Fix ICS04 to set right connection in verification

---

spec/ics-007-tendermint-client/README.md

Remove an unnecessary timing dependency in validity checks.
Add some normative guidance what validity checks are unrecoverable.

Remove an unnecessary fine grained timing dependency

---

spec/ics-007-tendermint-client/README.md

For the two clientState updates, I am not quite sure since they may have been done in the "verify" function. However, the "verify" function here differs quite a lot to the current [spec](https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/verification.md). Perhaps a new issue?

ICS 7: Tendermint client minor fixs

---

ibc/1_IBC_TERMINOLOGY.md

Fix broken ICS 25 link in "Handler Module" section.

docs: IBC terminology link fix

---

spec/ics-018-relayer-algorithms/README.md

The `connOpenTry` function in the channel spec has`counterpartyPrefix` argument, but the `ConnOpenTry` datagram does not have it.
```
function connOpenTry(
desiredIdentifier: Identifier,
counterpartyConnectionIdentifier: Identifier,
**counterpartyPrefix**: CommitmentPrefix,
counterpartyClientIdentifier: Identifier,
```

Add omitted counterpartyPrefix field in the ConnOpenTry datagram

---

misc/aspell_dict
spec.pdf
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-005-port-allocation/README.md
spec/ics-020-fungible-token-transfer/README.md
spec/ics-026-routing-module/README.md

Rework capability API in accordance with [ADR 3](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-003-dynamic-capability-store.md).
Closes https://github.com/cosmos/ics/issues/301
Closes https://github.com/cosmos/ics/issues/370

Rework capability API throughout specification

---

misc/aspell_dict
spec.pdf
spec/ics-002-client-semantics/README.md
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-006-solo-machine-client/README.md
spec/ics-007-tendermint-client/README.md
spec/ics-020-fungible-token-transfer/README.md
spec/ics-024-host-requirements/README.md
spec/ics-026-routing-module/README.md

Closes https://github.com/cosmos/ics/issues/439

Abstract height type

---

spec/ics-024-host-requirements/README.md

According to ICS 7, the correct Path is `"clients/{identifier}/consensusStates/{height}"` (plural).

Path typo fix

---

spec/ics-004-channel-and-packet-semantics/README.md

Closes #461 
This adds a recommended Acknowledgement envelope to the packet specification along with the definition of the acknowledgement algorithm.
I propose this under the RFC2119 keyword "SHOULD"
> 3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
>   may exist valid reasons in particular circumstances to ignore a
>   particular item, but the full implications must be understood and
>   carefully weighed before choosing a different course.
If you disagree with that, it could be reduced to "MAY":
> 5. MAY   This word, or the adjective "OPTIONAL", mean that an item is
>    truly optional.  One vendor may choose to include the item because a
>    particular marketplace requires it or because the vendor feels that
>    it enhances the product while another vendor may …

Add definition for Acknowledgement Envelope

---

spec/ics-003-connection-semantics/README.md

Solution candidate to close #459.
For a full discussion on the underlying problem, see [ibc-rs/disclosure-log](https://github.com/informalsystems/ibc-rs/blob/master/docs/disclosure-log.md#3-ics3-problems-due-to-version-negotiation).

ICS3 protocol fix for version negotiation 

---

misc/aspell_dict
spec.pdf
spec/ics-002-client-semantics/README.md
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md
spec/ics-006-solo-machine-client/README.md
spec/ics-007-tendermint-client/README.md
spec/ics-009-loopback-client/README.md
spec/ics-010-grandpa-client/README.md
spec/ics-018-relayer-algorithms/README.md
spec/ics-024-host-requirements/README.md

Closes https://github.com/cosmos/ics/issues/478

Asynchronous acknowledgements

---

spec.pdf
spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md

Flexible identifier & version selection.
Closes https://github.com/cosmos/ics/issues/462
Closes https://github.com/cosmos/ics/issues/465

Flexible identifier selection

---

spec/ics-005-port-allocation/README.md

When I was reading the spec/isc-005 , I found a code block that was not colored, so I fixed it.
https://github.com/cosmos/ics/tree/master/spec/ics-005-port-allocation

Fix syntax highlighting codeblock of ics-005

---

spec/ics-003-connection-semantics/README.md
spec/ics-004-channel-and-packet-semantics/README.md

Closes https://github.com/cosmos/ics/issues/491

Always use flexible identifier selection

---

spec/ics-002-client-semantics/README.md
spec/ics-003-connection-semantics/README.md
spec/ics-007-tendermint-client/README.md

Replaces https://github.com/cosmos/ics/pull/500 per discussion.

Delay period on a per-connection basis

---

spec/client/ics-007-tendermint-client/README.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-003-connection-semantics/README.md

Closes https://github.com/cosmos/ibc/issues/539
Split delay period into both a minimum time period which must have passed and a minimum number of blocks which must have passed in order to allow packets, acknowledgements, etc. to be processed.
Note that this breaks the connection handshake.

Update ICS 2, 3, 7 for hybrid delay period

---

spec/client/ics-006-solo-machine-client/README.md

ref: #562 
Addresses one problem outlined in the issue above. Enforces that the proof height is equivalent to the current client state sequence. 
**NOTE**: `VerifyClientState` is missing from ICS 03-connection as noted in #525. It is assumed that it will be inserted after `VerifyConnection` and before `VerifyClientConsensusState`

fix solo machine proof height sequence mismatch in connection handshake verification

---

spec/core/ics-004-channel-and-packet-semantics/README.md

This changes the ibc handler code, but no changes to the packets send over the wire, so non-breaking on the protocol layer.
It provides some needed information to allow fee incentivization for IBC packets, both in the ics20-2 proposal #577 as well as the more general relayer fee proposal #578

Update ICS-4 to pass relayer/signed to modules

---

spec/app/ics-029-fee-payment/README.md

It seemed to me "return relayer" is synonymous with "reverse relayer" and likely came from an old commit. I think it is most clear to use the defined terminology

use defined terms in relayer incentive spec

---

spec/core/ics-023-vector-commitments/README.md

Adding link to data definitions (defined as code - the only thing we have). 
The ICS-23 spec presents only high level requirements, but not a technical requirements (structure definitions, serialization, etc...).
ref: https://github.com/cosmos/cosmos-sdk/discussions/9331#discussioncomment-993092

Improve ics-023 spec

---

spec/core/ics-024-host-requirements/README.md

increase port identifier limit to 128 characters

---

spec/app/ics-027-interchain-accounts/README.md

This PR is updating the spec to have parity with the latest implementation. See [here](https://github.com/cosmos/ibc-go/pull/380).
Some improvements to the UX have been made by making use of ICS-04 channel negotiation (shoutout to @colin-axner  & @AdityaSripal for these ideas) as well as taking advantage of ICS-30 middleware architecture which replaces the previously existing `hooks` functionality for custom logic on `Success/Fail` of ICS-27 packets. 
I have also updated the introduction to be more clear. As well as various small updates throughout in order to align with the latest changes to the implementation. 
To be clear: **These changes are already implemented in code** & primarily effect the UX of the interchain accounts API & developer experience.

spec: updating ics27 spec to ensure parity with implementation

---

spec/client/ics-008-wasm-client/README.md

@AdityaSripal originally indicated [here](https://github.com/cosmos/ibc/pull/571#discussion_r654342052) that proof specs were necessary to fulfill the client interface, but than later specified that these are [no longer necessary](https://github.com/cosmos/ibc/pull/571#issuecomment-958946566)
In the ibc-go implementation case, I think the conclusion is that we would only expect the counterparty to use either use a 07-tendermint client or a 10-wasm client (with a connected tendermint client)?

remove ProofSpecs from Wasm spec

---

spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-026-routing-module/README.md

Improve handshake callbacks

---

spec/app/ics-027-interchain-accounts/README.md

Spec update based on [cosmos/ibc-go#778](https://github.com/cosmos/ibc-go/issues/778).
Since the portID for ICS20 is `transfer`, for naming consistency I propose to rename the `PortID` for the interchain accounts host submodule to `icahost` and the `PortPrefix` for the interchain accounts controller submodule to `icacontroller`.

ICS27: rename portID and portprefix

---

spec/app/ics-020-fungible-token-transfer/README.md

This PR updates the `FungibleTokenPacketSuccess` description in ICS20 to use `result` instead of `success`.
As `@simpletrondip` noticed in the [Agoric Discord](https://discord.com/channels/585576150827532298/766087740336635924/943031884580003890), there is a discrepancy between ICS20 and ICS04's descriptions of a successful acknowledgement.
In [the ICS20 spec](https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer#data-structures), the success data structure is described as:
```
interface FungibleTokenPacketSuccess {
// This is binary 0x01 base64 encoded
success: "AQ=="
}
```
however, in the [ICS004 spec](https://github.com/cosmos/ibc/tree/master/spec/core/ics-004-channel-and-packet-semantics#acknowledgement-envelope), there exists only `result` and `error`: …

ICS20: Use `result` instead of `success` in acknowledgement

---

spec/app/ics-020-fungible-token-transfer/README.md

Closes #625 
In ICS20, the channel should not close. Thus, the channel closing handshake should be aborted.

ICS20: onChanCloseInit must return error

---

spec/app/ics-020-fungible-token-transfer/README.md
spec/app/ics-027-interchain-accounts/README.md
spec/app/ics-029-fee-payment/README.md
spec/app/ics-030-middleware/README.md
spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-026-routing-module/README.md

aligns ICS 026 usage with function signature in ICS 004
closed #675, #674

ICS 004, ICS 026: add counterparty channel identifier argument to function call

---

README.md
meta/CONTRIBUTING.md
meta/PROCESS.md
meta/STANDARDS_COMMITTEE.md

I created a draft of the new contributing guidelines. I used https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md as template. 
Open questions:

Meta: Update contribution guidelines

---

spec/core/ics-003-connection-semantics/README.md

Add Verify Membership proof for packet receipt so we can prove a specific receipt value was stored under receipt path.
Needed for #636

ICS3: VerifyPacketReceipt

---

spec/core/ics-002-client-semantics/README.md

ICS2: VerifyPacketReceipt

---

spec/core/ics-002-client-semantics/README.md

ICS2: Generic Verification Methods

---

spec/app/ics-027-interchain-accounts/README.md

There were a couple of places where the port ID of the host was wrong.

ICS27: fix wrong port ID on host

---

spec/app/ics-028-cross-chain-validation/technical_specification.md

Closes https://github.com/cosmos/ibc/issues/743

ICS28: system aborted due to update aggregation logic

---

spec/app/ics-028-cross-chain-validation/technical_specification.md

Closes https://github.com/cosmos/ibc/issues/744

ICS28: Send SlashAcks only for downtime slash requests

---

README.md

As the section is described as
`All standards at or past the "Draft" stage are listed here in order of their ICS numbers, sorted by category.`

Add missing ics-008 in README.md

---

spec/app/ics-028-cross-chain-validation/technical_specification.md

Makes ICS28 consistent with https://github.com/cosmos/ibc/pull/731
Closes https://github.com/cosmos/ibc/issues/754

ICS28: Simplify sendPacket interface

---

spec/app/ics-029-fee-payment/README.md

Makes ICS29 consistent with https://github.com/cosmos/ibc/pull/731

ICS29: Simplify sendPacket interface

---

spec/app/ics-020-fungible-token-transfer/README.md

Makes ICS20 consistent with https://github.com/cosmos/ibc/pull/731
Closes https://github.com/cosmos/ibc/issues/709

ICS20: Simplify sendPacket interface

---

spec/core/ics-004-channel-and-packet-semantics/README.md

Closes https://github.com/cosmos/ibc/issues/708
Before merging update the calls to sendPacket throughout the standard, i.e.,

ICS4: Simplify sendPacket interface

---

spec/core/ics-004-channel-and-packet-semantics/README.md

- Fix `packetAcknowledgementPath` return `Path`
- Use string interpolation with `sequence` variable to be consistent with the rest of the variables

ICS4: Fix `packetAcknowledgementPath`

---

spec/client/ics-008-wasm-client/README.md

That's the convention for types in Rust.

Capitalize type name 'byte' in Rust code

---

spec/app/ics-028-cross-chain-validation/methods.md

Tackle https://github.com/cosmos/ibc/issues/768

ICS28: Use currentTimestamp() >= p.stopTime in StopConsumerChainProposalHandler

---

spec/app/ics-028-cross-chain-validation/data_structures.md
spec/app/ics-028-cross-chain-validation/methods.md

The consumer chain unbonding period is computed from the provider chain unbonding period. 
Closes https://github.com/cosmos/ibc/issues/673

ICS28: Add consumer UnbondingPeriod

---

spec/app/ics-028-cross-chain-validation/methods.md

Closes https://github.com/cosmos/ibc/issues/767

ICS28: Add conditions for CreateConsumerClient and StopConsumerChain

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Much cleaner fix to #698 
Supersedes: #722 
Each upgrade attempt is given a unique sequence, the error path is keyed on this sequence to avoid collisions
It also fixes another previously uncaught issue where relayers could submit proofs of channel state from previous upgrade attempts for the current upgrade handshake

Add upgrade sequences to avoid proof collisions

---

spec/core/ics-004-channel-and-packet-semantics/README.md

Allow for ORDERED_ALLOW_TIMEOUT, by writing a timeout receipt on destination chain if packet is received after timeout. Once the timeout receipt is written, it can be proven on counterparty chain to timeout packet without closing the channel

ICS4: Add ORDERED_ALLOW_TIMEOUT channel type

---

spec/core/ics-024-host-requirements/README.md

This brings the specification in line with the validation rules [applied](https://github.com/cosmos/ibc-go/blob/7d181821314d4bc6d0f8a5b885f293f5b975aed0/modules/core/24-host/validate.go#L76-L81) de facto by ibc-go, which have allowed channel IDs like "channel-0" to proliferate on deployed chains.

Bump minimal channel ID length to 8 characters

---

spec/app/ics-029-fee-payment/README.md

This just fixes some typos and adds an entry in the` History` section and updates the `modified` date, which should have been done in the [previous PR](https://github.com/cosmos/ibc/pull/779).

ICS-29: fix typos, update modified date

---

spec/app/ics-029-fee-payment/README.md

Update based on #629 
May need to help merge this @crodriguezvega

ICS29: Update Callbacks

---

spec/app/ics-027-interchain-accounts/README.md

ICS27: Update Callbacks

---

spec/app/ics-030-middleware/README.md

ICS30: Update callbacks

---

spec/core/ics-003-connection-semantics/README.md

Applies updates made in channel to remove crossing hellos in #629 to connections as well

ICS-3: Remove Crossing Hellos

---

spec/core/ics-004-channel-and-packet-semantics/README.md

Thanks to @colin-axner , a change was missed in removing crossing hellos in #629

ICS4: Fix crossing hellos removal for channel handshake

---

CHANGELOG.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-003-connection-semantics/README.md
spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-024-host-requirements/README.md

Closes: #764
I wasn't sure where to define the `validateSelfClient()` function. ibc-go puts it in the ICS-2 client keeper, with the Tendermint implementation. However, `validateSelfClient()` is a function that should be provided by the host, and so belongs in ICS-24 in my opinion. Since ICS-24 doesn't have any per-consensus-protocol sections, I opted for writing the generic declaration of `validateSelfClient()` in a new "Client state validation" section, and provide the Tendermint implementation as an example. I'm open to better ideas on how to organize this.
I faced another challenge. In [ibc-go](https://github.com/cosmos/ibc-go/blob/85893eebee1002f7ef74514b49c0981215405ceb/modules/core/02-client/keeper/keeper.go#L270), `validateSelfClient()` takes an `sdk.Context` as parameter and …

Put `ClientState` in `provableStore` and use it in `connOpen{Try,Ack}`

---

CHANGELOG.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Suggestion from implementation team. cc: @damiannolan

ICS4: Change upgrade state enums to match the open state enums

---

CHANGELOG.md
spec/core/ics-004-channel-and-packet-semantics/README.md

Fix sequence paths in ICS4 to align with ICS24 and implementation

ICS4: Fix Sequence Paths

---

CHANGELOG.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Suggestion from implementation team cc: @damiannolan @colin-axner

ICS4: Change location where upgrade sequence gets incremented

---

spec/app/ics-028-cross-chain-validation/README.md
spec/app/ics-028-cross-chain-validation/system_model_and_properties.md

Closes https://github.com/cosmos/ibc/issues/772

ICS28: Account for slashing in Bond-Based Consumer Voting Power property

---

README.md

Adds a link in README to the cross-chain queries spec

META: add CCQ to readme

---

CHANGELOG.md
spec/core/ics-002-client-semantics/README.md

Closes: #773
Closes: #689 
Closes: #693 
Closes: #694

ICS2: 02 client refactor

---

spec/core/ics-004-channel-and-packet-semantics/README.md

Abort sendPacket for packets with a zero timeout height and timestamp

---

CHANGELOG.md
spec/core/ics-004-channel-and-packet-semantics/README.md

ICS04: adds event emission in `recvPacket` to align with implementation

---

spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-026-routing-module/README.md

Remove deprecated comment from ICS4 and ICS26 READMEs

---

spec/core/ics-005-port-allocation/README.md

This is a minor fix in ICS5.
Signed-off-by: Jun Kimura <junkxdev@gmail.com>

ICS5: fix releasePort signature

---

spec/app/ics-721-nft-transfer/README.md

Adding `tokenData` to PacketData allows a zone to send application specific data to other zones, which enables richer application-level interactions. This is a minor change to the protocol yet it could be very useful for a slew of cross-chain use cases.

ICS721: Add tokenData to PacketData

---

spec/core/ics-003-connection-semantics/README.md
spec/core/ics-024-host-requirements/README.md

Hey guys, Protocol Lead for composable here. We've been working on extending ibc beyond cosmos and we've been working with the core ibc team on making this happen. Through this relationship we requested the 02-client refactor and now finally we're requesting this 03-connection extension.
03-connection as is requires that host state machines can introspect their own consensus state. Unfortunately this requirement is incompatible with every single blockchain we're working with (substrate, NEAR, ethereum). All of whom do not provide this sort of api to query past headers from within the blockchain runtime.
Inorder to keep to the IBC 03-connection specification and not skip the counterparty consensus state verification. We replace the requirement of host `ConsensusState` introspection, with a …

extend 03-connection with a proof object for chains that can't introspect their own consensus state.

---

spec/app/ics-028-cross-chain-validation/README.md
spec/app/ics-028-cross-chain-validation/data_structures.md
spec/app/ics-028-cross-chain-validation/methods.md

Closes https://github.com/cosmos/ibc/issues/825

ICS28: Reflect deferred unbonding completion in spec

---

CHANGELOG.md
spec/app/ics-027-interchain-accounts/README.md

Makes `icacontroller-` optional in controller port identifier.
Closes: #870

ICS27: make `icacontroller-` prefix optional

---

spec/app/ics-031-crosschain-queries/README.md
spec/client/ics-006-solo-machine-client/README.md

ICS-06: Solomachine Refactor

---

spec/app/ics-721-nft-transfer/README.md

Putting class/collection/contract level metadata into its own field `classData` instead of squeezing everything into `tokenData` is a better design that is called for by Stargaze/Ark/Juno teams who are relying on WASM contracts to implement and support ICS721.
As for the `memo` field, we are borrowing it from ICS20, there have been thorough discussions about why this field is introduced and how it's supposed to be used (please see #584 #842 #877).

ICS721: Add classData and memo fields to PacketData

---

spec/core/ics-003-connection-semantics/README.md

This PR addresses the comments of #530 that were still relevant. I will copy those here:
- In connOpenInit() and connOpenTry(), there is no error handling in the [spec](https://github.com/cosmos/ics/tree/master/spec/ics-003-connection-semantics#opening-handshake) when calling addConnectionToClient(). In the [code](https://github.com/cosmos/cosmos-sdk/blob/fe8a891f11dcefe708e43d53549beec808f98687/x/ibc/core/03-connection/keeper/keeper.go#L158), the transaction is aborted if the client does not exist.
- In the code of connOpenTry(), but not in the spec: 
- getting a consensus state from a given height [aborts on error](https://github.com/cosmos/cosmos-sdk/blob/fe8a891f11dcefe708e43d53549beec808f98687/x/ibc/core/03-connection/keeper/handshake.go#L93).
- In the code of connOpenAck(), but not …

ICS3: fix inconsistencies in the spec and code of connection handshake

---

spec/client/ics-007-tendermint-client/README.md

Followup PR from https://github.com/cosmos/ibc/pull/914.
Adds [`nextValidatorsHash` to `TendermintSignedHeader`](https://github.com/tendermint/tendermint/blob/main/proto/tendermint/types/types.proto#L74), which is used when creating a new `ConsensuState` in `UpdateState`.

ICS07: add `nextValidatorsHash` to `TendermintSignedHeader`

---

spec/client/ics-006-solo-machine-client/README.md
spec/client/ics-007-tendermint-client/README.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-024-host-requirements/README.md
spec/core/ics-026-routing-module/README.md

Several updates that I discussed with @AdityaSripal:
- Changed signatures of `verifyMembership` and `verifyNonMembership` in ICS 02 to return an error instead of a boolean. Pseudocode for these functions has also been updated in ICS 06 and ICS 07.
- Used `provableStore.get(...)` and `provableStore.set(...)` in ICS 06 and ICS 07 to keep consistency with the other specs.
- Updated `createClient` function in ICS 02 and `initialise` in ICS 06 and 07 to reflect the [latest changes in ibc-go](https://github.com/cosmos/ibc-go/pull/2936).
- Updated `checkForMisbehaviour` in ICS 07 to extend check of conflicting header and to add check for valid misbehavior of BFT time violation.

Updates to ICS 02, 06, 07 and 26

---

spec/app/ics-031-crosschain-queries/README.md

This is a tiny change to make the path more consistent with the format used in [ICS24](https://github.com/cosmos/ibc/blob/main/spec/core/ics-024-host-requirements/README.md#path-space).

ICS31: small change in path to follow consistency

---

spec/app/ics-028-cross-chain-validation/system_model_and_properties.md

The *Provider Slashing Warranty* was too strict. The adapted property allows for the provider to delay slashing a validator that misbehaved on a consumer, as long as the stake of those validator cannot unbond. 
This enables the implementation of the jail throttling mechanism (see https://github.com/cosmos/interchain-security/pull/682).

Relax Provider Slashing Warranty property

---

spec/app/ics-721-nft-transfer/README.md

Probably a typo, the `source` is not a parameter `createOutgoingPacket` function should receive, it is a bool taken from `classId`

ICS721: Update README.md

---

spec/app/ics-031-crosschain-queries/README.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-003-connection-semantics/README.md
spec/core/ics-003-connection-semantics/UPGRADES.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
spec/core/ics-025-handler-interface/README.md
spec/relayer/ics-018-relayer-algorithms/README.md

This PR:
- closes #888 
- fixes the inconsistencies in naming between `queryClient` and `queryClientState` in favour of the latter.
- fixes the inconsistencies of using the generic `verifyMembership` and `verifyNonMembership` functions declared in ICS 02 where the client state is passed as first argument.
closes: #888

fix usage of generic verify functions

---

spec/client/ics-006-solo-machine-client/README.md
spec/client/ics-007-tendermint-client/README.md
spec/core/ics-002-client-semantics/README.md

I noticed that solo machine functions using the client state assumed that they were part of a `ClientState` class, while the rest of the specs assumed that the client state was passed as an argument. This PR changes solo machine to be consistent with the rest

fix: consistent use of client state functions

---

spec/client/ics-006-solo-machine-client/README.md
spec/client/ics-007-tendermint-client/README.md
spec/client/ics-009-loopback-cilent/README.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-024-host-requirements/README.md
spec/core/ics-026-routing-module/README.md

Remove deprecated concept of `ClientType`
closes: https://github.com/cosmos/ibc/issues/810
closes: https://github.com/cosmos/ibc/issues/856

ICS 02: remove concept of client type

---

spec/app/ics-020-fungible-token-transfer/README.md
spec/app/ics-027-interchain-accounts/README.md
spec/app/ics-029-fee-payment/README.md
spec/app/ics-030-middleware/README.md
spec/client/ics-006-solo-machine-client/README.md
spec/client/ics-007-tendermint-client/README.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-003-connection-semantics/README.md
spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-005-port-allocation/README.md
spec/core/ics-023-vector-commitments/README.md
spec/core/ics-024-host-requirements/README.md
spec/core/ics-025-handler-interface/README.md
spec/core/ics-026-routing-module/README.md
spec/ics-001-ics-standard/README.md
spec/ics-template.md

The PR adds a column to the table on the top of each spec for an optional list of implementations' versions that are compatible with the spec. 
This is [an example](https://github.com/cosmos/ibc/blob/carlos/add-version-compatibility-column/spec/core/ics-002-client-semantics/README.md) of how it looks. Unfortunately the table is too width and needs a scroll bar.

add version compatibility column

---

spec/relayer/ics-018-relayer-algorithms/README.md

As #934 said, I found some mistakes about the ```proofHeight``` in ICS18.
closes: #934

Fix some mistakes in ICS18

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

- Validates that the new connection is still correct counterparty in connectionUpgrade
- Use old connection until channel is OPEN again
Closes: #947

Validate Connection for Channel Upgrade

---

spec/app/ics-020-fungible-token-transfer/README.md
spec/app/ics-100-atomic-swap/README.md
spec/app/ics-721-nft-transfer/README.md

ICS 20, 100, and 721 contain a mistyped variable name in the pseudocode definition of `onAcknowledgePacket`:
The formal parameter name is `acknowledgement`, but in the function body it is referred to by `ack`.
Since this is a small fix, I did not open an issue or update the ICS metadata. Please lmk if I should do so.
&nbsp;
&nbsp;
_Found while writing the [ICS-20 spec in Quint](https://github.com/informalsystems/quint/tree/main/examples/cosmos/ics20), simply by copy-pasting._

Fix mistyped variable name

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Refactor according to @colin-axner suggestions
- Store upgrade in separate path and keep original channel in state until channel is OPEN
- Pause new packets and flush in-flight packets before channel can reopen
----
Happy path handshake is done
Cancel/Timeout still needs to change

Upgradability fixes

---

spec/core/ics-026-routing-module/README.md

This PR will add a missing method to the ModuleCallbacks interface required by the [IBCModule](https://github.com/cosmos/ibc-go/blob/main/modules/core/05-port/types/module.go#L14) interface.
The missing method is OnChanCloseInit which is required to allow a module to initiale a closing of a channel and is referred to in the same [ICS-026](https://github.com/cosmos/ibc/tree/main/spec/core/ics-026-routing-module). An example of its implementation in the transfer module can be found [here](https://github.com/cosmos/ibc-go/blob/main/modules/apps/transfer/ibc_module.go#L148).

Add missing method to ModuleCallbacks interface

---

spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

This PR makes the following changes:
- Remove notion of upgrade states and instead only add FLUSHING and FLUSHINGCOMPLETE to state enum
- Make INITUpgrade authority gated
- Start timers on TRY and ACK messages
- Add ChanUpgradeConfirm to ensure both sides are aware of counterparty upgrade timeout before moving to FLUSHCOMPLETE
- Add packet processing logic

Upgrade Refactors

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

ICS 04 (upgrades): fix counterparty connection hops in `chanUpgradeOpen`

---

spec/app/ics-027-interchain-accounts/README.md

It additionally...
closes #650

ICS27: add support for unordered channels/implement upgrade callbacks

---

spec/core/ics-004-channel-and-packet-semantics/README.md

These two paths were out-of-sync with the current IBC implementation, as deployed throughout the ecosystem.

ics-004: fix packetReceiptPath and packetCommitmentPath

---

README.md

Fixed the github repo hyperlink for the relayer in Rust

Fix README.md link to the Rust relayer

---

spec/client/ics-006-solo-machine-client/README.md
spec/client/ics-009-loopback-cilent/README.md

Updates for https://github.com/cosmos/ibc-go/pull/4429.

ICS 06: updates for using unprefixed path in sign bytes

---

README.md

Adding a link to the [CCV module](https://github.com/cosmos/interchain-security/tree/main/x/ccv) and moving it to the [Candidate stage](https://github.com/cosmos/ibc/blob/main/meta/PROCESS.md).

tiny: add link to CCV in the README

---

spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

closes: #1024
closes: #1015
closes: #1023

ICS004: Remove last packet sent

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

While re-reviewing the channel upgrades spec to regain context, I noticed a few small inconsistencies in code style in the pseudo code and a few suggestions for different wording in several cases.

Small consistency updates for channel upgrade spec

---

spec/app/ics-028-cross-chain-validation/data_structures.md

<Description>
A duplication error is fixed in the following document:
"spec/app/ics-028-cross-chain-validation/data_structures.md"
Same sentences repeated twice consecutively. 
<Test>
No test required

Remove a duplication error in document

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Closes: #1052 
Closes: #1053 
Closes: #1054

ICS4: Fix UpgradeSequence logic

---

spec/app/ics-020-fungible-token-transfer/README.md

Previously the units for `timeoutTimestamp` were not specified and it's unclear whether they were unix seconds or nanoseconds.
This specifies that the units are unix nanoseconds as per the Go implementation: https://github.com/cosmos/ibc-go/blob/d0cf5b64dc8756206dad6c922e3530535ab78b79/proto/ibc/applications/transfer/v1/tx.proto#L47

specify units of `timeoutTimestamp` in ICS20

---

meta/CONTRIBUTING.md
spec/app/ics-029-fee-payment/README.md
spec/app/ics-100-atomic-swap/README.md
spec/core/ics-002-client-semantics/README.md
spec/core/ics-003-connection-semantics/UPGRADES.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
spec/relayer/ics-018-relayer-algorithms/README.md

This pull request includes a series of grammatical corrections and command fixes across various ICS standards. These updates aim to enhance the clarity and accuracy of the documentation. Below is a summary of the key changes:
1. **ICS-004 Channel and Packet Semantics:** Corrected "portIdentifer" to "portIdentifier" and "channelIdentifer" to "channelIdentifier" in various sections.
2. **ICS-003 Connection Semantics:** Updated "wish the take advantage" to "wish to take advantage."
3. **ICS-018 Relayer Algorithms:** Fixed "such by including" to "such as by including."
4. **ICS-002 Client Semantics:** Revised "knowns" to "knows."
5. **ICS-100 Atomic Swap:** Addressed multiple errors, changing "occurence" to "occurrence," "transfering" to "transferring," and "an user" to "a user."
6. **ICS-029 …

ICS Documentation: Grammar and Command Fixes

---

spec/ics-001-ics-standard/README.md

The `kind` field is used in all the specs header, however it is not described in ics-001.

ics001: add ics header field description

---

spec/core/ics-004-channel-and-packet-semantics/README.md
spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Closes: #1060 
Closes: #1061 
- Add NextSequenceSend field to upgrade struct
- Add path for counterpartyNextSequenceSend in private store
- Correctly set packet recv and ack sequences if order has changed
- Defensive check on RecvPacket
- Comment detailing implementation details for pruning

ICS4: Implement Packet Sequence Logic for upgrades

---

README.md

I went thru a few different configurations and ultimately think this is the easiest way to ask for the CTA. If people integrate just these Transport/Core standards, they should be able to interoperate w IBC regardless of what their underlying client/relayer impl looks like, this is why I didn't add those in. 
We want people to contribute to specific client/relayer impl if they wish as well, but those are not essential for interoperability, as the 02-client, 03-connection, 04-channel etc etc specs are.

fix: update spec organisation for CTA

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

this is called in `restoreChannel` so appears this wasn't removed during a refactor.

Remove double call to restore callback.

---

spec/core/ics-004-channel-and-packet-semantics/README.md

Found during review of https://github.com/cosmos/ibc-go/pull/5668.

fix: allow recv packet when channel state is flush complete

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
spec/core/ics-004-channel-and-packet-semantics/channel-upgrade-flow.png

this PR adds a diagram to the `UPGRADES.md` file in `ics-004-channel-and-packet-semantics` to depict the happy path of a channel upgrade.

Add diagram to channel upgradability spec

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

Writes error receipt for previous upgrade attempt if we initialize a new one. This allows the counterparty to cancel their upgrade and retry on the latest attempt

ICS4: write error receipt on existing upgrade attempt if we are reinitializing

---

spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

If on TRY, the sequence is the same but the upgrade doesn't exist. Then the counterparty upgrade is stale so we must write upgrade error for that sequence

ICS4: fix off-by-one error in non-crossing-hello case

---

spec/app/ics-020-fungible-token-transfer/README.md

Fixes one item mentioned in https://github.com/cosmos/ibc-go/issues/65:
> Spec uses undefined newAddress() in [onChanOpenInit](https://github.com/cosmos/ics/tree/eb31a56467a48cd7eb4c2232705ad0fc632f9a19/spec/ics-020-fungible-token-transfer#routing-module-callbacks) and onChanOpenTry and stores it in a map under the channel id. Code uses a deterministic function of the portID and channelID, ie. newAddress(portID, channelID). With crossing-hellos we could have a safety problem according to this spec as we can execute onChanOpenInit (creates escrow address E1), then createOutgoingPacket using E1, then onChanOpenTry we creates a new escrow address E2 that replaces E1, so money is gone. It seems that at code level we don't have this problem as implementation does not follow spec, i.e., it …

fix: use port ID and channel ID as inputs of the escrow address generation

---

.github/workflows/link-check.yml

Node16 is deprecated and Actions using it will stop working 3rd of June
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

upgrade checkout action to version using node20

---

meta/CONTRIBUTING.md
spec/core/ics-003-connection-semantics/UPGRADES.md

- Fixed a broken hyperlink to core IBC standards
- Fixed incorrect spelling of TypeScript type

chore: fix link & typo

---

spec/app/ics-020-fungible-token-transfer/README.md

Following up on the discussion from the walkthrough, it does seem like we can simplify the logic of `revertInflightChanges` ([I actually had also hinted that to Aditya when I first reviewed the spec...](https://github.com/cosmos/ibc/pull/1090#discussion_r1552390936))
To make it easier for everyone to reason about this (although please double check that I haven't made any mistake), the following outlines what happens with the escrow accounts and forwarding account assuming that there is a timeout or error ack and changes on the middle hop need to be reverted. The `receivedPacket` is the received packet on the middle hop and the `sentPacket` is the packet sent from the middle hop as a result of forwarding.
- receive packet as source of tokens:
transfer tokens …

ICS20v2 path forwarding: simplify revert in-flight changes

---

spec/app/ics-020-fungible-token-transfer/README.md

ICS20v2: use protobuf encoding for packet data of v2

---

spec/core/v2/ics-002-client-semantics/README.md

Closes https://github.com/cosmos/ibc/issues/1136

02-client-TAOv2

---

spec/eureka/README.md

Either the parameter name or the usage within the function need to be renamed if I understand this correctly.

Fix variable name in Eureka spec

---

spec/app/ics-020-fungible-token-transfer/README.md
spec/app/ics-020-fungible-token-transfer/v1/README.md

This PR introduces IBC v2 TAO support for the ics20 v1 and v2 trying to capture all the internal discussions. 
Closes https://github.com/cosmos/ibc/issues/1141

ics20-tao-v2-support

---

spec/core/v2/ics-004-packet-semantics/PACKET.md

The following is the Packet spec that uses only hashing rather than the cbor encoding in the previous spec. This is meant to allow reviewers to compare the two options.
Benefits:
- No standardized encoding allows implementation by virtually any platform with low maintanence burden
- Canonical by construction
Cons:
- Must specify a unique commitment scheme for the internal packet data and acknowledgement rather than relying on existing encoding
- Multiple hashes might be slow and expensive in certain environments (e.g. EVM, and ZKVM)

Packet Spec: Hash App data rather than standardizing encoding

---

spec/core/v2/ics-004-packet-semantics/PACKET.md

Closes: https://github.com/cosmos/ibc/issues/1167
Creates fixed 32-byte commitment by moving protocol byte into the final hash to improve gas costs on solidity

ICS4: Create 32 byte commitment

---

spec/core/ics-004-channel-and-packet-semantics/README.md

Fix outdated description for optimistic send

---

spec/core/ics-023-vector-commitments/README.md

This pull request contains changes to improve clarity, correctness and structure.
Description correction:
Corrected `lexographically` to `lexicographically`
Corrected `neightbors` to `neighbors`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

CHANGELOG.md
spec/eureka/README.md

I hope my correction will contribute to the project's development. Thank you for the time you gave me.

Refined text by fixing typos and improving clarity

---

spec/ics-001-ics-standard/README.md

This pull request addresses inconsistencies in the terminology of the `README.md` file within the `spec/ics-001-ics-standard` directory. Specifically, the term "inter-chain" has been updated to "interchain," aligning with standard usage in the Cosmos ecosystem documentation.  
- Replaced all instances of "inter-chain" and "Inter-chain" with "interchain" and "Interchain."  
- Improved clarity and consistency across the document.  
The updates ensure consistent terminology and adhere to the preferred style for referring to interchain standards in the Cosmos ecosystem.  
Allowing maintainers to edit this PR is enabled.

Fix: Standardize "Interchain" Terminology in README 

---

spec/eureka/README.md

1. Fix incomplete sentence in comment
2. In the `ProveCounterparty` section, rename channel to client

docs: update IBC v2 spec

---

spec/client/ics-009-loopback-cilent/README.md

While reviewing the `updateState` function in the Loopback Client spec, I noticed that `header.height` is used, but `header` is never defined. However, just above, `height = getSelfHeight()` correctly retrieves the height of the local ledger.  
This change replaces `header.height` with `height`, ensuring that the function uses the properly initialized variable.

docs: fix undefined `header` in `updateState`
